## Large file transfer

Often if the researcher has many files to upload or the files are large in size, we will need to provide alternative methods of upload. We currently have two options available for large file transfer where sFTP is easier to set up but slower while GLOBUS takes a bit more setup but faster.

Before providing access, try to get a sense of how big the transfer will be. `df -h` on Arctic server and datateam server - look at current space available

### sFTP

As a team member for login info. 

> After you login, you can add a folder with your last name to add your files. If you need more detailed access instructions, I have included the link here for your convenience: https://help.nceas.ucsb.edu/NCEAS/help/remote_file_access

**Option 1: SSH via the Terminal**
https://pages.github.nceas.ucsb.edu/NCEAS/help/connecting_to_linux_using_ssh.html

**Option 2: Cyberduck instructions**

To use Cyberduck to transfer local files onto the Datateam server:

1) Open Cyberduck.
2) Check that you have the latest version (Cyberduck -> Check for Update...). If not, download and install the latest (you may need  Jeanette to enter a password).
3) Click "Open Connection".
4) From the drop-down, choose "SFTP (Secure File Transfer Protocol)".
5) Enter "datateam.nceas.ucsb.edu" for Server.
6) Enter your username and password.
7) Connect.

From here, you can drag and drop files to and from the server.

### Globus Endpoint

1. arctic-data-center
2. #arctic-data-center
3. login using your credentials on the datateam server

Remember to remove the files on the datateam server after you finish a ticket to free up space.
