### Additional email templates

#### Deadlines
If the PI is checking about dates/timing:

> We process submissions in the order in which they are received, and yours still has a few ahead of it in our queue. Are you facing any deadlines? If so, we may be able to expedite publication of your submission.

#### Pre-assigned DOI
If the PI needs a DOI right away:

> We can provide you with a pre-assigned DOI that you can reference in your paper. However, please note that it will not become active until after we have finished processing your submission and the package is published. 

#### Best practices

>We noticed that the data files submitted are in _____ format. We recommend conversion of these files into a plain text/csv (OR ANOTHER APPROPRIATE OPEN-SOURCE) format in order to facilitate an accurate transfer of information to future researchers and ensure preservation of the data in perpetuity. Below are some linked articles about data science best practices that the NSF Arctic Data Center adheres to:  
DataONE - https://www.dataone.org/best-practices  
"Some Simple Guidelines for Effective Data Management" -  http://onlinelibrary.wiley.com/doi/10.1890/0012-9623-90.2.205/full  
"Good Enough Practices in Scientific Computing" - http://arxiv.org/pdf/1609.00037v1.pdf  

#### Adding metadata via R

>KNB does not support direct uploading of EML metadata files through the website (we have a webform that creates metadata), but you can upload your data and metadata through R!

>[Here](https://nceas.github.io/sasap-training/materials/reproducible-analysis-in-r/data-documentation-and-publishing.html#publishing-data-from-r) are some training materials we have that use both the `dataone` and `datapack` packages. It explains how to set your authentication token, build a package from metadata and data files, and publish the package to one of our test sites. I definitely recommend practicing on a test site prior to publishing to the production site your first time through. You can point to the KNB test node (dev.nceas.ucsb.edu) using this command: `d1c <- D1Client("STAGING2", "urn:node:mnTestKNB")`

>If you prefer, there are Java, Python, MATLAB, and Bash/cURL clients as well.


####  Nesting

>Nesting data packages under a common "parent" is beneficial so that all data packages funded by the same award can be found in one place. This way additional data packages can be added to the group without altering existing ones. Once we process all the "child" data packages you upload, we can group them under the same "parent". The parent will not contain any data files itself, but will be populated with metadata only. Please view an example of a parent data package [here](https://arcticdata.io/catalog/#view/doi:10.18739/A2G95H). Would you like your submission(s) grouped with the other data packages funded by the same award? If so, we are happy to do all this grouping for you.


#### Finding multiple data packages

>If linking to multiple data packages, you can send a link to the profile associated with the submitter’s ORCID iD and it will display all their data packages.
	e.g.: https://arcticdata.io/catalog/#profile/http://orcid.org/0000-0002-2604-4533
	
	
#### NSF ARC data submission policy

>The NSF Section for Arctic Sciences (ARC) program managers check compliance with their data policies when checking annual reports. Generally, NSF ARC requires that fully quality controlled data be uploaded within 6 months of collection for Arctic Observing Network (AON) projects, or within 2 years of collection (or by end of the grant) for other ARC funded projects. Additionally, complete metadata must be submitted within two years of collection or before the end of the award, whichever comes first. (NSF policies include special exceptions for Arctic Social Sciences Program (ASSP) awards and other awards that contain sensitive data, including human subjects data and data that are governed by an Institutional Review Board policy. These special conditions exist for sharing social science data that are ethically or legally sensitive or at risk of decontextualization.) Please find an overview of the NSF ARC policies [here](https://arcticdata.io/submit/#who-must-submit) and the full policy information [here](https://www.nsf.gov/pubs/2014/nsf14584/nsf14584.htm#grantcond).

>Investigators should upload their data to the [Arctic Data Center](https://arcticdata.io), or, where appropriate, to another community endorsed data archive that ensures the longevity, interpretation, public accessibility, and preservation of the data (e.g., GenBank, NCEI). Local and university web pages generally are not sufficient as an archive. Data preservation should be part of the institutional mission and data must remain accessible even if funding for the archive wanes (i.e., succession plans are in place). We would be happy to discuss the suitability of various archival locations with you further. In order to provide a central location for discovery of ARC-funded data, a metadata record must always be uploaded to the Arctic Data Center even when another community archive is used.


#### Linking ORCiD and LDAP accounts

> First create an account at orcid.org/register if you have not already. After that account registration is complete, login to the KNB with your ORCID iD here: https://knb.ecoinformatics.org/#share. Next, hover over the icon on the top right and choose "My Profile". Then, click the "Settings" tab and scroll down to "Add Another Account". Enter your name or username from your Morpho account and select yourself (your name should populate as an option). Click the "+". You will then need to log out of knb.ecoinformatics.org and then log back in with your old LDAP account (click "have an existing account", and enter your Morpho credentials with the organization set to "unaffiliated") to finalize the linkage between the two accounts. Navigate to "My Profile" and "Settings" to confirm the linkage.

> After completing this, all of your previously submitted data pacakges should show up on your KNB "My Profile" page, whether you are logged in using your ORCiD or Morpho account, and you will be able to submit data either using Morpho or our web interface.

> Or, try reversing my instructions - log in first using your Morpho account (by clicking the "existing account" button and selecting organization "unaffiliated"), look for your ORCiD account, then log out and back in with ORCiD to confirm the linkage.


