## Example Solr queries

```{r echo = FALSE, warning = FALSE, message = FALSE}
library(knitr)
library(magrittr)
library(kableExtra)
library(tibble)

cn <- dataone::CNode('PROD')
mn <- dataone::getMNode(cn,'urn:node:ARCTIC')

format_query_result <- function(query_result) {
  query_result %>% 
    knitr::kable(format = "html") %>% 
    kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>% 
    kableExtra::scroll_box(box_css = "overflow-x: auto") #display concisely
}
```

### Find everything

```{r}
result <- dataone::query(mn, list(q="*:*",
                                  fl="*",
                                  rows="5"),
                         as = "data.frame")
```

```{r echo = FALSE}
format_query_result(result)
```


### Query a wildcard expression 

```{r type = "markdown-table"}
#find any id that starts with arctic-data.
result <- dataone::query(mn, list(q="id:arctic-data.*",
                                  fl="*",
                                  rows="5"),
                         as = "data.frame")
```

```{r echo = FALSE}
format_query_result(result)
```

### Query multiple fields 

```{r}
result <- dataone::query(mn, list(q="title:*soil*+AND+origin:*Ludwig*",
                        fl="title",
                        rows="5"),
                        as = "data.frame")
```

```{r echo = FALSE}
format_query_result(result)
```

```{r}
result <- dataone::query(mn, list(q="title:*soil*+OR+origin:*Ludwig*",
                                  fl="title",
                                  rows="5"),
                         as = "data.frame")
```


```{r echo = FALSE}
format_query_result(result)
```


### Query multiple conditions within one field

```{r}
result <- dataone::query(mn, list(q="title:(*soil*+AND+*carbon*)",
                                  fl="title",
                                  rows="5"),
                         as = "data.frame") 
```

```{r echo = FALSE}
format_query_result(result)
```

### Use NOT in a query

Just add `-` before a query parameter!

```{r}
result <- dataone::query(mn, list(q="title:(*soil*+AND+-*carbon*)",
                                  fl="title",
                                  rows="5"),
                         as = "data.frame")
```

```{r echo = FALSE}
format_query_result(result)
```

### Query a coordinating node

```{r}
result <- dataone::query(cn, list(q="title:*soil*+AND+origin:*Ludwig*",
                                  fl="title",
                                  rows="5"),
                         as = "data.frame")
```

```{r echo = FALSE}
format_query_result(result)
```

### Use facets

All resource maps with > 100 data objects that are _not_ on the Arctic Data Center:

```
https://cn.dataone.org/cn/v2/query/solr/?q=resourceMap:*+AND+-datasource:*ARCTIC*&rows=0&facet=true&facet.field=resourceMap&facet.mincount=100
```