# Edit data packages

```{r, echo = FALSE}
chapter <- "../workflows/edit_data_packages/"
sections <- dir(path = chapter, pattern = ".Rmd$")
children <- paste0(chapter, sections)
```

```{r, child = children}
```

# Explore EML

```{r, echo = FALSE}
chapter <- "../workflows/explore_eml/"
sections <- dir(path = chapter, pattern = ".Rmd$")
children <- paste0(chapter, sections)
```

```{r, child = children}
```

# Edit EML

```{r, echo = FALSE}
chapter <- "../workflows/edit_eml/"
sections <- dir(path = chapter, pattern = ".Rmd$")
children <- paste0(chapter, sections)
```

```{r, child = children}
```

# PI correspondence

```{r, echo = FALSE}
chapter <- "../workflows/pi_correspondence/"
sections <- dir(path = chapter, pattern = ".Rmd$")
children <- paste0(chapter, sections)
```

```{r, child = children}
```

# Miscellaneous file types

```{r, echo = FALSE}
chapter <- "../workflows/misc_file_types/"
sections <- dir(path = chapter, pattern = ".Rmd$")
children <- paste0(chapter, sections)
```

```{r, child = children}
```

# Wrangle data

```{r, echo = FALSE}
chapter <- "../workflows/wrangle_data/"
sections <- dir(path = chapter, pattern = ".Rmd$")
children <- paste0(chapter, sections)
```

```{r, child = children}
```

# Solr queries

```{r, echo = FALSE}
chapter <- "../workflows/solr_queries/"
sections <- dir(path = chapter, pattern = ".Rmd$")
children <- paste0(chapter, sections)
```

```{r, child = children}
```

# ADC Web Submissions

```{r, echo = FALSE}
chapter <- "../workflows/adc_web_submissions/"
sections <- dir(path = chapter, pattern = ".Rmd$")
children <- paste0(chapter, sections)
```

```{r, child = children}
```

## More resources

- Solr's [The Standard Query Parser](https://cwiki.apache.org/confluence/display/solr/The+Standard+Query+Parser) docs (high level of detail)
- Another quick reference: https://wiki.apache.org/solr/SolrQuerySyntax
- http://www.solrtutorial.com/