## Query Solr

Solr is queried via what's called an HTTP API (Application Programming Interface).
Practically, what this means it that you can visit a URL (web address) in a web browser to execute a query.
This may be a little bit weird at first but I hope some examples will make it more clear.

So I said you visit a URL to query Solr.
But what address do you visit?
For the Arctic Data Center (https://arcticdata.io), every Solr query starts with a base URL of https://arcticdata.io/metacat/d1/mn/v2/query/solr.
If you visit that URL, you will see a list of fields Solr is storing for the Objects it indexes:

```xml
<ns2:queryEngineDescription xmlns:ns2="http://ns.dataone.org/service/types/v1.1">
  <queryEngineVersion>3.6.2.2012.12.18.19.52.59</queryEngineVersion>
  <name>solr</name>
  <queryField>
    <name>abstract</name>
    <description>
      The full text of the abstract as provided in the science metadata document.
    </description>
    ...truncated...
```

You can see that there is a large set of queryable fields, though, as I said above, not all types of Objects will have values set for all of the possible fields because some fields do not make sense for some Objects (e.g., `title` for a CSV).

### Parts of a Query

Each Solr query is comprised of a number of parameters.
These are like arguments to a function in R, but they are entered as parts of a URL.

The most common parameters are:

- `q`: The query. This is like `subset` or `dplyr::filter` in R
- `fl`: What fields are returned for the documents that match your query (`q`). If not set, all fields are returned.
- `rows`: The maximum number of documents to return. Solr will truncate your result if the result size is greater than `rows`.
- `sort`: Sorts the result by the values in the given Solr field (e.g., sort by date uploaded)

To use these parameters, we append to the base URL like this:

`https://arcticdata.io/metacat/d1/mn/v2/query/solr/?q={QUERY}&fl={FIELDS}&rows={ROWS}`

and we replace the text inside `{}` with the value we want for each parameter.
Note that the parameters can come in any order so the following is equivalent:

`https://arcticdata.io/metacat/d1/mn/v2/query/solr/?fl={FIELDS}&rows={ROWS}&q={QUERY}`

The first parameter in the URL must have a '?' in front of it and all subsequent parameters must have an '&' between them.
It's really easy to get the URL wrong when typing it in manually like this so be sure to double-check your URL and think critically about the result: Solr tries to always return something even if it's not what you intended.

### Constructing a Query

The query ('q') parameter uses a syntax that looks like `field:value`, where `field` is one of the Solr fields and `value` is an expression.
The expression can match a specific value exactly, e.g.,

- `https://arcticdata.io/metacat/d1/mn/v2/query/solr/?q=identifier:arctic-data.7747.1`
- `https://arcticdata.io/metacat/d1/mn/v2/query/solr/?q=identifier:"doi:10.5065/D60P0X4S"`

which finds the Solr document for a specific Object by PID (identifier).
Note that in the second example, the DOI PID is surrounded in double quotes.
This is because Solr has [reserved characters](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html), of which ':' is one, so we have to help Solr by surrounding values with reserved characters in them in quotes (as I did here) or escaping them.

Queries can take on a more advanced form such as a wildcard expression:

- `https://arcticdata.io/metacat/d1/mn/v2/query/solr/?q=identifier:arctic-data.*`

finds all the Objects that start with "arctic-data." followed by anything ("*")

- `https://arcticdata.io/metacat/d1/mn/v2/query/solr/?q=title:*soil*`

finds all the Objects with the word "soil" somewhere in the title.

- `https://arcticdata.io/metacat/d1/mn/v2/query/solr/?q=origin:*Stafford*+AND+title:Bering Strait&fl=title&sort=title+desc&rows=10`

finds 10 Objects where one of the EML `creator`s has a name that contains the substring "Stafford" and the `title` contains the substring "Bering Strait", sorted by `title` (descending order).
Note that the `+AND+` between the `origin` and `title` query above specifies that both conditions must be true for a Solr document to be returned.
We could've also switched the `+AND+` to `+OR+` and/or added more conditions to the query.

Here's a slightly more advanced one:

- `https://arcticdata.io/metacat/d1/mn/v2/query/solr/?q=formatType:METADATA+AND+-obsoletedBy:*&sort=dateUploaded+desc&rows=25`

This query is the query MetacatUI uses to fill in the https://arcticdata.io/catalog/ page.
Notice the `-obsoletedBy:*`.
The '-' before the field inverts the expression so this part of the query means "things that have no `obsoletedBy` value set".

We can also just find everything:

- `https://arcticdata.io/metacat/d1/mn/v2/query/solr/?q=*:*`

finds any value in any field.