## Data Portals

> Create a custom, branded portal for your research topic or lab group that spans datasets in the Arctic Data Center – available for all users. Branded portals provide a convenient, readily customized way to communicate your science, your team, your data, and related data from within the Arctic Data Center. The portals feature makes highlighting and sharing related datasets easy for researchers.

General information on data portals can be found on the main page:  <a href = 'https://arcticdata.io/data-portals/' target='_blank'>https://arcticdata.io/data-portals/</a> 
 
 ## My portals
  My portals allows members of the Arctic Data Center Team to view all the portals currently created. This can be found in `Settings` under the `My Portals` section.
  
 ## Creating Data Filters
 Useful search terms to use:
 - NSF award number
 - Geographic Region
 - Keywords
 - Access permissions
 
 ### Custom Filters
 Please ask Jeanette for more assistance
 
 ### Set Access Permissions
 For some portals such as PerCS portal, will need to be added by running `set_access()`. Please see the specific portal for the exact arguments to pass.
 
