# Editing system metadata

Every object on the ADC (or the KNB) has "system metadata". An object's system metadata have information about the file itself, such as the name of the file (`fileName`), the format (`formatId`), who the `rightsHolder` is, what the `accessPolicy` is, and more. Sometimes we will need to edit system metadata in order to make sure that things on the webpage display correctly, or to ensure a file downloads from the website with the correct file name and extension.

Although the majority of system metadata changes that need to be made are done automatically, sometimes we need to change aspects of the system metadata (or 'sysmeta' for short) manually.

```{r, child = '../workflows/edit_data_packages/edit_sysmeta.Rmd'}
```


## Exercise 5 {.exercise}

Sometimes the system doesn't recognize the file types properly. For example you have a csv file but the File type on the website says `Microsoft Excel` 

* Read the system metadata in from the data file you uploaded [previously](#exercise-4).
* Check to make sure the `fileName` and `formatId` are set correctly (the extension in `fileName` should match the `formatId`).
* Update the system metadata if necessary.
