# Introduction to Solr

Solr is what's known as an index.
More specifically, it's a piece of software that we install with every instance of Metacat which we use to query all of the Objects Metacat stores (metadata, data, resource maps, etc.). [Metacat](https://www.dataone.org/software-tools/metacat) is our underlying metadata catalog and the foundation of our data repositories for both the CN and all MNs.
Every Object in Metacat will have a corresponding Solr document for it that contains information about that Object.
Each type of Object will have a different set of fields in its Solr document.
For example, an EML document will have a `title` field (corresponding to the EML document's `<title>` element), while a CSV will not.

The fields that go into a Solr document are populated by information such as:

- The System Metadata (fileName, accessPolicy, etc)
- The Object itself (e.g. title, creators, etc. for an EML record)
- Additional computed fields (e.g., a geohash for quick spatial search)

Indexing the Object's Metacat stores lets us execute some interesting and very useful queries such as:

- What are the most recently updated datasets?
- What Metadata and Data Objects are in a given Data Package?
- What is the total size (in terms of disk space) of all Objects stored in Metacat?

```{r, child = '../workflows/query_with_solr/query_solr.Rmd'}
```

## Key takeaways

- Find out what you can query at https://arcticdata.io/metacat/d1/mn/v2/query/solr
- The Solr HTTP API is what the R `dataone` package uses when you run `query`
- Pass a token if you want to include non-public-readable objects in the results (you often do!)

These skills are highly transferable. Note the syntax of the URL for a Google search.

## More resources

- Solr's [The Standard Query Parser](https://cwiki.apache.org/confluence/display/solr/The+Standard+Query+Parser) docs (high level of detail)
- Another quick reference: https://wiki.apache.org/solr/SolrQuerySyntax
- http://www.solrtutorial.com/