--- 
title: "NCEAS Data Team Training"
author: "Jesse Goldstein, Dominic Mullen, Jeanette Clark, Irene Steves, Mitchell Maier, Bryce Mecum, Peter Slaughter, Emily O'Dean"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    highlight: tango
    css: ../styles.css
documentclass: book
github-repo: rstudio/datateam-training
description: "This is a training guide and reference resource for NCEAS data team members working on the SASAP and Arctic Data Center projects"
favicon: "favicon.ico"
---

# Welcome to NCEAS! {-}

## First day to-dos {-}

* Get a tour of the office from Ginger, Jesse, or Dom
* Fill out required paperwork from Ana (room 309)
* Have Gabriella take your picture (room 309)
* Set up the remainder of your accounts


## Account information {-}

* <a href="https://identity.nceas.ucsb.edu/identity/cgi-bin/ldapweb.cgi?cfg=account" target="_blank">LDAP</a> - this should be set up prior to your start date in order to help get other accounts set. This account and password control your access to:
    + arcticdata <a href="https://support.nceas.ucsb.edu/rt/" target="_blank">RT queue</a> 
    + GitHub Enterprise - <a href="https://github.nceas.ucsb.edu/KNB/arctic-data/" target="_blank">arctic-data</a>
* Datateam server - follow instructions in email from Nick at NCEAS to reset your datateam password in the terminal
* <a href="https://orcid.org/register" target="_blank">ORCiD</a> - create an account
    + Login to <a href="https://test.arcticdata.io" target="_blank">test.arcticdata.io</a> with your ORCID iD
* <a href="http://nceas.slack.com" target="_blank">NCEAS Slack</a> - get an invite from <a href="http://slack.nceas.ucsb.edu" target="_blank">slack.nceas.ucsb.edu</a>
    + Channels to join: #arctica, #arcticbot, #computing, #datateam, #devteam, #social
    + Introduce yourself in #datateam and then use that channel to ask Jesse or Dom to make you an administrator on test.arcticdata.io
* Arctic Data Center Team - after creation of ORCiD and sign-in to both arcticdata.io and test.arcticdata.io, request addition to the admin group from Dom or Jesse in Slack
* GitHub - if you do not have a public GitHub account already, please register for one <a href="https://github.com/join?source=header-home" target="_blank">here</a>
* <a href="https://docs.google.com/spreadsheets/d/1Jf7IkSf8Vqu51xv1DDaTNCrTAZd0RMNH9ExZw0eyH4I/edit#gid=948090118" target="_blank">Schedule</a> - fill out anticipated quarterly schedule. Note there are separate tabs for each week AND a general schedule tab for the quarter.
* <a href="https://timekeeping.ucsb.edu/" target="_blank">Electronic Timekeeping</a> - make sure you can log on to electronic timekeeping
via your UCSBNetID and password. Log your hours for your first day! Under today's date select 'Hours Worked' under the Pay Code column, enter the amount of hours under the Amount column, and finally click the 'Save' button in the top right. At the end of every two-week pay period you will also need to click the 'Approve Timecard' button in order to submit your timecard.  
<a href="https://timekeeping.ucsb.edu/sites/default/files/employee_hours_worked_0.pdf" target="_blank">Detailed Instructions</a>


## NCEAS Events {-}

NCEAS hosts a number of events that you are encouraged to attend. Keep an eye on your email but the recurring events are:

* Roundtable
    + weekly presentation and discussion of research by a visiting or local scientist
    + Wednesdays at 12:15 in the lounge
* Coffee Klatch
    + coffee, socializing, and news updates for NCEAS
    + Tuesdays at 10:30 in the lounge
* Salad Potluck
    + potluck salad and socializing, bring a topping or side to share!
    + second Tuesday of the month, 12:15 in the lounge
