## Set DataONE nodes 
Tell R which repo you want to work with by setting the coordinating node (CN) and member node (MN) using the appropriate code below.

```{block, type = "warning"}
A note on nodes - be very careful about what you publish on production nodes (`PROD`, or arcticdata.io). These nodes should NEVER be used to publish test or training data sets.
```

### Staging (Test) nodes
```{r, eval = F}
# ADC (test.arcticdata.io)
cnT <- dataone::CNode('STAGING')
mnT <- dataone::getMNode(cn,'urn:node:mnTestARCTIC')

# KNB (dev.nceas.ucsb.edu)
cnT2 <- dataone::CNode("STAGING2")
mnT2 <- dataone::getMNode(cn, "urn:node:mnTestKNB")
```

### Production nodes
```{r, eval = F}
# ADC (arcticdata.io)
cn <- dataone::CNode('PROD')
mn <- dataone::getMNode(cn,'urn:node:ARCTIC')

# KNB (knb.ecoinformatics.org)
cn2 <- dataone::CNode("PROD")
mn2 <- dataone::getMNode(cn, "urn:node:KNB")
```

More DataONE STAGING nodes can be found [here](https://cn-stage.test.dataone.org/cn/v2/node).
More DataONE PROD nodes can be found [here](https://cn.dataone.org/cn/v2/node).
