## Update a data file

To update a data file, you need to do three things:

1)  update the object itself, 
2)  update the metadata that describes that object
3)  update the resource map (which affiliates the object with the metadata).

The `arcticdatautils::update_object` function takes care of the first of these tasks. As arguments, update object takes the member node instance you are working in, the `pid` of the object to be updated, the path to the new version of that object on your computer, and the format id of the object.

The code will look like this (very similar to the `publish_object` function call):

```{r, eval = F}
id_new <- update_object(adc_test, 
                        pid = "the data pid you need to update",
                        path = "path/to/new/file.csv",
                        format_id = "text/csv")
```


```{block, type = "note"}
You will need to be explicit about your `format_id` here based on the file type. A list of format IDs can be found [here](https://cn.dataone.org/cn/v2/formats) on the DataONE website.
Use line 2 (Id:) exactly, character for character.
```


To acomplish the second task, you will need to update the metadata using the EML package. This is covered in [Chapter 4](https://nceas.github.io/datateam-training/training/editing-eml-in-r.html). After you update a file, you will always need to update the metadata because parts of the `physical` section (such as the file size, checksum) will be different, and it may also require different attribute information.

Once you have updated your metadata and saved it, you can update the package itself.