## Set the project section 

The project section in an EML document is automatically filled out by the metacatUI editor. It sets the project title and project personnel to the submission's title and creators.  Most of the time at least some of this information is incorrect and we need to update it.  

Start by searching for the funding information using <a href = 'https://www.nsf.gov/awardsearch/' target='_blank'>NSF's award search</a>. This will give us the project title, abstract, and personnel - along with some additional metadata.  

Using this information we will set the title, personnel, and funding number. For NSF funded projects prepend the funding number with "NSF". If there are multiple awards associated with one dataset then additional `funding`, `title`, and `personnel` elements should be added to reflect the additional awards.    


```
doc$dataset$project$funding$para[[1]] <- 'NSF 1503846'

doc$dataset$project$title[[1]] <- 'Collaborative Research: Reconciling conflicting Arctic temperature and fire reconstructions using multi-proxy records from lake sediments north of the Brooks Range, Alaska

doc$dataset$project$personnel[[1]] <- eml$personnel(individualName = eml$individualName(givenName = 'Yongsong', surName = 'Huang'),
                                                    role = 'Principal Investigator')
doc$dataset$project$personnel[[2]] <- eml$personnel(individualName = eml$individualName(givenName = 'James', surName = 'Russell'),
                                                    role = 'co Principal Investigator')
```

There is also a helper function `eml_nsf_to_project()` that can help do the searching for you. Just verify that the information retrieved is correct.
```
# update NSF awards data
awards <- c("1311655", "1417987", "1417993") # list of award numbers
proj <- eml_nsf_to_project(awards) #helper function

doc$dataset$project <- proj
```

On the web form right now only fills in the funding field. We need instructions on how to convert that to the new awards formatting until the form is updated to include these fields:

```
project$award$funderName # required
project$award$title # required
project$award$awardNumber
project$award$funderIdentifier
```

Information can be found in using the  <a href = 'https://gitlab.com/crossref/open_funder_registry/-/tree/master' target='_blank'>Open Funder Registry</a>. If a award title cannot be found you can use the dataset title.
